/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRegisterRouteImport } from './routes/api/register'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as ApiAgentsRouteImport } from './routes/api/agents'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRegisterRoute = ApiRegisterRouteImport.update({
  id: '/api/register',
  path: '/api/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsRoute = ApiAgentsRouteImport.update({
  id: '/api/agents',
  path: '/api/agents',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/agents': typeof ApiAgentsRoute
  '/api/events': typeof ApiEventsRoute
  '/api/register': typeof ApiRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/agents': typeof ApiAgentsRoute
  '/api/events': typeof ApiEventsRoute
  '/api/register': typeof ApiRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/agents': typeof ApiAgentsRoute
  '/api/events': typeof ApiEventsRoute
  '/api/register': typeof ApiRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/agents' | '/api/events' | '/api/register'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/agents' | '/api/events' | '/api/register'
  id: '__root__' | '/' | '/api/agents' | '/api/events' | '/api/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAgentsRoute: typeof ApiAgentsRoute
  ApiEventsRoute: typeof ApiEventsRoute
  ApiRegisterRoute: typeof ApiRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/register': {
      id: '/api/register'
      path: '/api/register'
      fullPath: '/api/register'
      preLoaderRoute: typeof ApiRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents': {
      id: '/api/agents'
      path: '/api/agents'
      fullPath: '/api/agents'
      preLoaderRoute: typeof ApiAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAgentsRoute: ApiAgentsRoute,
  ApiEventsRoute: ApiEventsRoute,
  ApiRegisterRoute: ApiRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
